### ISSUE TITLE
Projet absent de la liste sur Edge (pbm de cache HTTP)

### ISSUE THREAD

**Issue by matcornic** [soprasteria/dad#37]
**Symptome :** un projet qui vient d'être créé n'est pas visible dans la liste des projets.
**Origine :** problème de cache HTTP sur les données retournées par le serveur.
**Contexte :** Microsoft Edge
**Contournement :**  Utiliser un autre navigateur (Chrome/Firefox) ou vider manuellement le cache de Edge.

**Comment by Thiht** [comment]
Voir : 
* http://stackoverflow.com/a/29246795
* http://stackoverflow.com/a/36415045

**Comment by matcornic** [comment]
En gros, un petit middleware sur le /api et on est bon.
