### ISSUE TITLE
Pouvoir identifier les projets pour lesquels aucun travail n'a été fourni

### ISSUE THREAD

**Issue by axellb** [soprasteria/dad#39]
Etre capable de différencier :
   - N/A => projet qui n'a rien de renseigné
   - No goal => projet qui a un état des lieux de renseigné mais pas de goal
   -  x % => projet qui a des goals de renseigné
Màj de la documentation
   - Formule qui explique le calcul
   - Possibilités offertes par la recherche
   - Màj des screenshots

**Comment by Thiht** [comment]
Fixed with #40
